[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'python39', 'poetry']

[phases.install]
cmds = [
  'cd frontend && yarn install && yarn build',
  'cd backend && poetry install'
]

[start]
cmd = 'cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT' 